// Brisa i18n — Spanish (default) + English
const strings = {
  es: {
    // App
    appName: 'Brisa',
    appTagline: 'Tu espacio de calma',

    // Navigation
    navHome: 'Inicio',
    navData: 'Datos',
    navJournal: 'Diario',
    navProfile: 'Perfil',
    navChat: 'Chat',

    // Home
    homeGreeting: 'Hola',
    homeQuestion: '¿Cómo estás?',
    homeMainButton: 'Registrar',
    homeStreak: 'días seguidos',
    homeLastLog: 'Último registro',

    // Log Flow — Initial
    logTitle: '¿Qué está pasando?',
    logOptionA: 'Estoy teniendo un episodio',
    logOptionB: 'Ya pasó mi episodio',
    logOptionC: 'No estoy segura',
    logOptionD: 'Solo estoy checkeando',

    // Log Flow — Steps
    howDoYouFeel: '¿Cómo te sientes?',
    feelScale: 'Del 0 al 10, ¿cómo te sientes?',
    urgeScale: 'Del 0 al 10, ¿qué tanta urgencia de tocarte sientes?',
    notAtAll: 'Nada',
    veryMuch: 'Mucho',
    calm: 'En calma',
    overwhelmed: 'Abrumada',

    // Breathing
    breatheTitle: 'Respiremos juntos',
    breatheInhale: 'Inhala',
    breatheHold: 'Sostén',
    breatheExhale: 'Exhala',
    breatheReady: '¿Lista?',
    breatheStart: 'Comenzar',
    breatheDone: 'Bien hecho ✨',

    // Body location
    whereTouch: '¿Dónde te estás tocando?',
    eyebrows: 'Cejas',
    eyelashes: 'Pestañas',
    scalp: 'Cabeza',
    other: 'Otro',
    specify: 'Especificar...',

    // Blocker
    rideTheWave: 'RIDE THE WAVE OF DISCOMFORT',
    blockerMessage: 'Sé que puede dar pereza, pero vamos a buscar un blocker: guantes, pañuelo de cabeza, gorro, un juguete...',
    cantRightNow: 'No puedo ahora',
    foundOne: 'Encontré uno',

    // Trigger/Behavior/Result
    defineTogethertitle: 'Definamos juntos',
    trigger: 'Trigger (¿qué lo provocó?)',
    behavior: 'Comportamiento (¿qué hiciste?)',
    result: 'Resultado (¿qué pasó?)',

    // Pulling
    didYouPull: '¿Te sacaste algún pelito?',
    yes: 'Sí',
    no: 'No',
    whatDidYouGet: '¿Qué obtuviste de tocarte/jalarte?',

    // Mindfulness
    observeTitle: 'Vamos a observar sin juzgar',
    whatUrgeFeels: '¿Cómo se siente la urgencia? (Conecta con tu cuerpo)',
    whatSensations: '¿Qué sensación sientes con más fuerza? (Elige 1)',

    // Sensations
    tightness: 'Tensión',
    pressure: 'Presión',
    contraction: 'Contracción',
    restlessness: 'Inquietud',
    shallowBreath: 'Respiración corta',
    burning: 'Ardor',
    tension: 'Tensión muscular',
    clenching: 'Apretar',
    heat: 'Calor',
    pitInStomach: 'Nudo en el estómago',
    buzzing: 'Hormigueo',

    // Body side
    bodySideQuestion: '¿Es más del lado derecho o izquierdo? ¿En el frente, medio o atrás? ¿Dónde sientes más fuerte?',
    right: 'Derecha',
    left: 'Izquierda',
    front: 'Frente',
    middle: 'Medio',
    back: 'Atrás',

    // Curiosity
    otherSensations: '¿Hay otras sensaciones? ¿Qué pasa cuando te pones curiosa sobre ellas? ¿Cambian?',
    followSensations: 'Sigue tus sensaciones por los próximos 30 segundos. No intentes hacer nada con ellas, solo obsérvalas.',
    doTheyChange: '¿Cambian cuando las observas con curiosidad?',

    // Break / Check-in
    breakTitle: '¿Cómo te sientes ahora?',
    wantToContinue: '¿Quieres continuar con el ejercicio?',
    continueYes: 'Sí, continuar',
    continueNo: 'Estoy bien, terminar',

    // Grounding messages
    groundingTouch: 'En momentos difíciles, toca algo que te ancle al presente (textura, peso, respiración).',
    groundingTest: 'Cada momento difícil es un test de tu mente para ver si mantienes el control.',
    groundingAccept: 'Acepta el sentimiento, ride the wave of discomfort.',
    groundingIdentity: 'Nuestra identidad es una historia que nos hemos estado contando. El momento en que decides actuar diferente, salir de viejos patrones, empiezas a expandir tu identidad.',

    // Celebration
    celebrate: '¡Celebra cada pequeño progreso, no importa qué tan pequeño sea!',
    celebrateCheckin: '¡Qué bien que estás aquí! Solo el hecho de checkear es un progreso enorme.',
    youDidIt: '¡Lo lograste! 💛',
    logSaved: 'Registro guardado',

    // Location context
    whereAreYou: '¿Dónde estás?',
    whatDoing: '¿Qué estás haciendo?',

    // Path B
    breatheOrFinish: '¿Quieres hacer un ejercicio de respiración o terminar el registro?',
    doBreathing: 'Ejercicio de respiración',
    finishLog: 'Terminar registro',

    // Data
    dataTitle: 'Tu datos',
    dataByHour: 'Por hora del día',
    dataByLocation: 'Lugares más comunes',
    dataByBodyPart: 'Zonas más tocadas',
    dataByTrigger: 'Triggers más comunes',
    dataTotalLogs: 'Total de registros',
    dataThisWeek: 'Esta semana',
    dataThisMonth: 'Este mes',

    // Journal
    journalTitle: 'Mi diario',
    journalNew: 'Nueva entrada',
    journalPlaceholder: 'Escribe lo que sientes...',
    journalSaved: 'Entrada guardada',

    // Profile
    profileTitle: 'Mi perfil',
    profileLogs: 'Registros',
    profileStreak: 'Racha',
    profileDays: 'días',
    profileSettings: 'Configuración',
    profileLanguage: 'Idioma',
    profileNotifications: 'Notificaciones',
    profileNotifTime: 'Hora de notificación',
    profileNotifMessage: 'Mensaje personalizado',
    profileStreakType: 'Tipo de racha',
    streakLogged: 'Días que registré',
    streakPullFree: 'Días sin tocarme',

    // Chat
    chatTitle: 'Habla con Brisa',
    chatPlaceholder: 'Escribe o dicta tu mensaje...',
    chatWelcome: 'Hola, soy Brisa 🌿 Estoy aquí para acompañarte. Puedes preguntarme lo que quieras sobre tricotilomanía.',

    // Common
    next: 'Siguiente',
    back: 'Atrás',
    done: 'Listo',
    save: 'Guardar',
    cancel: 'Cancelar',
    skip: 'Saltar',
    close: 'Cerrar',

    // Voice
    tapToSpeak: 'Toca para dictar',
    listening: 'Escuchando...',
  },

  en: {
    appName: 'Brisa',
    appTagline: 'Your calm space',
    navHome: 'Home',
    navData: 'Data',
    navJournal: 'Journal',
    navProfile: 'Profile',
    navChat: 'Chat',
    homeGreeting: 'Hi',
    homeQuestion: 'How are you?',
    homeMainButton: 'Log',
    homeStreak: 'day streak',
    homeLastLog: 'Last log',
    logTitle: "What's happening?",
    logOptionA: "I'm having an episode right now",
    logOptionB: 'My episode already passed',
    logOptionC: "I'm not sure",
    logOptionD: 'Just checking in',
    howDoYouFeel: 'How do you feel?',
    feelScale: 'From 0 to 10, how do you feel?',
    urgeScale: 'From 0 to 10, how strong is the urge to touch?',
    notAtAll: 'Not at all',
    veryMuch: 'Very much',
    calm: 'Calm',
    overwhelmed: 'Overwhelmed',
    breatheTitle: "Let's breathe together",
    breatheInhale: 'Inhale',
    breatheHold: 'Hold',
    breatheExhale: 'Exhale',
    breatheReady: 'Ready?',
    breatheStart: 'Start',
    breatheDone: 'Well done ✨',
    whereTouch: 'Where are you touching?',
    eyebrows: 'Eyebrows',
    eyelashes: 'Eyelashes',
    scalp: 'Scalp',
    other: 'Other',
    specify: 'Specify...',
    rideTheWave: 'RIDE THE WAVE OF DISCOMFORT',
    blockerMessage: "I know it can feel like a lot, but let's find a blocker: gloves, headscarf, hat, a fidget toy...",
    cantRightNow: "I can't right now",
    foundOne: 'Found one',
    defineTogethertitle: "Let's define together",
    trigger: 'Trigger (what caused it?)',
    behavior: 'Behavior (what did you do?)',
    result: 'Result (what happened?)',
    didYouPull: 'Did you pull any hair?',
    yes: 'Yes',
    no: 'No',
    whatDidYouGet: 'What did you get from pulling/touching?',
    observeTitle: "Let's observe without judging",
    whatUrgeFeels: 'What does the urge feel like? (Check in with your body)',
    whatSensations: 'What sensation do you feel most strongly? (Choose 1)',
    tightness: 'Tightness',
    pressure: 'Pressure',
    contraction: 'Contraction',
    restlessness: 'Restlessness',
    shallowBreath: 'Shallow breath',
    burning: 'Burning',
    tension: 'Tension',
    clenching: 'Clenching',
    heat: 'Heat',
    pitInStomach: 'Pit in stomach',
    buzzing: 'Buzzing',
    bodySideQuestion: 'Is it more on the right side or the left? In the front, middle, or back? Where do you feel most strongly?',
    right: 'Right',
    left: 'Left',
    front: 'Front',
    middle: 'Middle',
    back: 'Back',
    otherSensations: 'Are there other sensations? What happens when you get curious about them? Do they change?',
    followSensations: 'Follow your sensations over the next 30 seconds. Not trying to do anything to or about them, simply observing them.',
    doTheyChange: 'Do they change at all when you observe them with an attitude of curiosity?',
    breakTitle: 'How do you feel now?',
    wantToContinue: 'Do you want to continue the exercise?',
    continueYes: 'Yes, continue',
    continueNo: "I'm good, finish",
    groundingTouch: 'In difficult moments, touch something that anchors you to the present (texture, weight, breath).',
    groundingTest: 'Every difficult moment is a test from your mind to see if you keep control.',
    groundingAccept: 'Accept the feeling, ride the wave of discomfort.',
    groundingIdentity: "Our identity is a story we've been telling ourselves. The moment you decide to act differently, to step outside old patterns, you start expanding your identity.",
    celebrate: 'Celebrate every small progress, no matter how small!',
    celebrateCheckin: "So glad you're here! Just checking in is huge progress.",
    youDidIt: 'You did it! 💛',
    logSaved: 'Log saved',
    whereAreYou: 'Where are you?',
    whatDoing: 'What are you doing?',
    breatheOrFinish: 'Would you like to do a breathing exercise or finish the log?',
    doBreathing: 'Breathing exercise',
    finishLog: 'Finish log',
    dataTitle: 'Your data',
    dataByHour: 'By hour of day',
    dataByLocation: 'Most common places',
    dataByBodyPart: 'Most touched areas',
    dataByTrigger: 'Most common triggers',
    dataTotalLogs: 'Total logs',
    dataThisWeek: 'This week',
    dataThisMonth: 'This month',
    journalTitle: 'My journal',
    journalNew: 'New entry',
    journalPlaceholder: 'Write what you feel...',
    journalSaved: 'Entry saved',
    profileTitle: 'My profile',
    profileLogs: 'Logs',
    profileStreak: 'Streak',
    profileDays: 'days',
    profileSettings: 'Settings',
    profileLanguage: 'Language',
    profileNotifications: 'Notifications',
    profileNotifTime: 'Notification time',
    profileNotifMessage: 'Custom message',
    profileStreakType: 'Streak type',
    streakLogged: 'Days I logged',
    streakPullFree: 'Pull-free days',
    chatTitle: 'Talk to Brisa',
    chatPlaceholder: 'Type or dictate your message...',
    chatWelcome: "Hi, I'm Brisa 🌿 I'm here to support you. Ask me anything about trichotillomania.",
    next: 'Next',
    back: 'Back',
    done: 'Done',
    save: 'Save',
    cancel: 'Cancel',
    skip: 'Skip',
    close: 'Close',
    tapToSpeak: 'Tap to dictate',
    listening: 'Listening...',
  },
};

export default strings;
